name: nf-core lint

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install nf-core tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install "nf-core==3.5.2"

      - name: Run nf-core lint
        run: nf-core pipelines lint .
